### ISSUE TITLE
Random system doesn't work 

### ISSUE THREAD

**Issue by Pezhin** [Barroth42/Morales_CSCI2270_FinalProject#14]
If you set the same players number, you would always get the same cards.
For example, I set player number to 1 and I would always get a 3 of Clubs, 9 of Spades and when I input "hit", I will always "drew a 10 of Hearts and busted".

```
    random_shuffle(decklist.begin(), decklist.end());
```

does not works here.

**Comment by nicjohnston** [comment]
Could you please provide a more specific series of commands that cause this problem?
Thanks.

**Comment by Pezhin** [comment]
This is the first time I run the program
![image](https://cloud.githubusercontent.com/assets/11862132/7426579/b5473aa4-ef85-11e4-8d92-ad379ff68661.png)

after this exit the executable and restart it 

![image](https://cloud.githubusercontent.com/assets/11862132/7426588/cf6866a6-ef85-11e4-9f91-164b1fe314aa.png)
The result is exactly same. So I don't think the random_shuffle function is working

**Comment by nicjohnston** [comment]
My results did not repeat over 8 tests using 1 player and 0 AI players, so could you provide some details about the version of C++ and the operating system you are testing this on?

**Comment by Pezhin** [comment]
I think I should try this on other platform.
